pipeline {
    options {
        // set a timeout of 30 minutes for this pipeline
        timeout(time: 30, unit: 'MINUTES')
    }
    agent {
      node {
        // TODO: run this simple pipeline on jenkins 'master' node
      }
    }

    stages {

        stage('stage 1') {
            steps {
                script {
                    openshift.withCluster() {
                        openshift.withProject() {
                                echo "stage 1: using project: ${openshift.project()} in cluster ${openshift.cluster()}"
                        }
                    }
                }
            }
        }
    agent{
        node{
         label 'master'
        }

     }

       stage('stage 2') {
            steps {
                sh 'echo hello from stage 2!. This is the last stage...'
            }
        }
      stage('manual approval') {
            steps {
                timeout(time: 60, unit: 'MINUTES') {
                    input message: "Move to stage 3?"
                }
            }
       } 
    
    }
}

